### ISSUE TITLE
good

### ISSUE THREAD

**Issue by shabaz4825** [TokyoTF/live-rec#1]
hii your app is good could please add cam4 and stripchat

**Comment by shabaz4825** [comment]
stipchat and cam4 video not recording it showing java script error

**Comment by shabaz4825** [comment]
in new update

**Comment by TokyoTF** [comment]
Thanks for mentioning the error, now add that the data and the rec list are saved

See the [latest version](https://github.com/TokyoTF/live-rec/releases/latest) with all the changes
