### ISSUE TITLE
Javascript Error

### ISSUE THREAD

**Issue by misterkoko** [TokyoTF/live-rec#3]
Hello

I got a javascript error while adding a model and now I can't remove the model, move between models or add new models because it throws errors.

![image](https://github.com/user-attachments/assets/106ee8c7-f56c-4e57-bd0e-793c33e8060b)

Also I have a feature request if you could perhaps implement the ability so we could rename recordings

example:

instead of model-site-dd-MM-YYYY_HH-MM-ss.mkv we could perhaps manually set it to model-YYYYMMdd-HHMMss.ts inside the program

maybe also an option to move the recording to a different folder when it's finished

Visually the program looks very nice, keep it up.

EDIT:

Forgot to say this was the windows portable version if that's relevant.

**Comment by TokyoTF** [comment]
@misterkoko Sorry for so many errors in the application, could you test if the latest version fixes these errors?

I also added what you told me about the date format

Remember to delete the configuration file so that a new one is generated. It is located in documents/live-rec/config.json
You can also backup the reclist and paste it, no problem.

See the [latest version](https://github.com/TokyoTF/live-rec/releases/latest) with all the changes

**Comment by misterkoko** [comment]
The error messages are gone, now after adding a few models it just takes some time to load the models / it gets stuck on "loading" the model

![image](https://github.com/user-attachments/assets/35e13ae9-e087-434c-b56d-1f64b339c343)

After some time the "loading" models appeared, then I had to press the play button and the resolution and Start REC appeared. If I don't press the play button, the resolution and Start REC don't appear.

I haven't tested yet what it does when a model goes private / offline / away / hidden and then comes back online - if the resolution and Start REC appear back or not.

Again, tested this on windows portable version, sorry I can't provide any errors since I get none. Maybe you can replicate this by adding a bunch of cb models.

**Comment by TokyoTF** [comment]
One of the reasons is because in the case of CB when making many request in a few seconds sending status 429, this will block the current request and the following by throwing that error. That is why it is loading

A possible solution is to add more delay than I already had from 150ms to 410ms

**Comment by misterkoko** [comment]
Could a possible fix be so your program detects if error 429 has been thrown and it auto retries so you don't need to manually press the play button. You can probably have incremental delay


function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function retryRequestWithBackoff(retryCount, initialDelay) {
  let delay = initialDelay;

  for (let i = 0; i < retryCount; i++) {
    try {
      await makeRequest();
      break; 
    } catch (error) {
      if (error.status === 429) {
        console.log('Request failed with 429, retrying after ${delay}ms...');
        await sleep(delay);
        delay = delay * 2 + Math.random() * 100;
      } else {
        throw error; 
      }
    }
  }
}

retryRequestWithBackoff(5, 150); 

async function makeRequest() {

  throw { status: 429, message: "Too Many Requests" };
}

Sorry for bad formatting can't get it right in the comment

**Comment by misterkoko** [comment]
```javascript
<script>
  import { onMount } from 'svelte';

  let maxRetries = 5; // Maximum number of retries
  let initialDelay = 150; // Initial delay in milliseconds

  async function makeRequestWithBackoff(i = 0) {
    let delay = initialDelay * Math.pow(2, i); // Exponential backoff delay

    try {
      // Replace this with your actual request logic
      const response = await fetch('https://api.example.com/data');

      if (!response.ok) {
        if (response.status === 429 && i < maxRetries) {
          console.log(`Retrying after ${delay}ms due to 429 error (attempt ${i + 1})...`);
          await new Promise(resolve => setTimeout(resolve, delay));
          return makeRequestWithBackoff(i + 1);
        } else {
          throw new Error(`Request failed with status ${response.status}`);
        }
      }

      const data = await response.json();
      console.log('Request succeeded:', data);
      return data;

    } catch (error) {
      console.error('Request failed:', error);
      // Handle the error or provide feedback to the user
    }
  }

  onMount(() => {
    makeRequestWithBackoff();
  });
</script>
```
example for retry with delay in svelte (not sure if the code is correct, maybe it will help you with ideas)
